### PR TITLE
feature: enabled multi-line parsing of env files

### PR DESCRIPTION
**Pull request by VijoPlays**
With this PR it should be possible to read an .env variable from a file with multiple lines.

One minor issue for the tests:
> I can't seem to get the EnvReader to find the new env file I created for the tests. Would be nice if you could take a look and merge this in the next couple of days.

### CODE REVIEW

**Comment by bolorundurowb** [comment]
Thanks @VijoPlays

**Comment by bolorundurowb** [comment]
This closes #29

**Comment by bolorundurowb** [comment]
@VijoPlays I have to revert this PR as the multi line reader doesnt work as expected and the test for it fails

**Comment by VijoPlays** [comment]
> @VijoPlays I have to revert this PR as the multi line reader doesnt work as expected and the test for it fails

@bolorundurowb yes, that's the issue I mentioned in the PR:

> I can't seem to get the EnvReader to find the new env file I created for the tests. Would be nice if you could take a look and merge this in the next couple of days.

The reader itself behaves correctly, it's probably just a pathing error or something in the tests.

**Comment by VijoPlays** [comment]
Reopened in #52

**Pull request merged**
